# Generated by Django 3.0.7 on 2020-06-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200606_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='session_start',
            field=models.DateField(null=True),
        ),
    ]
