# Generated by Django 3.0.7 on 2020-06-09 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200608_1442'),
        ('courses', '0002_auto_20200609_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Staff'),
        ),
    ]
